Softea.ResourceForm/Controllers/ResourceFormController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Dolph.SmartContentPicker.Fields;
using Orchard;
using Orchard.AntiSpam.Models;
using Orchard.ContentManagement;
using Orchard.ContentPicker.Fields;
using Orchard.Core.Common.Fields;
using Orchard.Core.Title.Models;
using Orchard.Fields.Fields;
using Orchard.Localization;
using Orchard.Localization.Models;
using Orchard.Localization.Services;
using Orchard.Logging;
using Orchard.Tasks.Indexing;
using Orchard.Themes;
using Softea.ResourceForm.Services;
using Softea.ResourceForm.ViewModels;

namespace Softea.ResourceForm.Controllers
{
    [Themed]
    public class ResourceFormController : Controller
    {
        private readonly IContentManager contentManager;
        private readonly ICultureManager cultureManager;
        private readonly IEmailService emailManager;
        private readonly IOrchardServices orchardServices;
        private readonly IIndexingTaskManager _indexingTasks;
        private string actualLanguage = "sk-SK";
        private const string ReCaptchaUrl = "http://www.google.com/recaptcha/api";
        private ILogger Logger;

        public ResourceFormController(IContentManager contentManager, ICultureManager cultureManager, IEmailService emailService, IOrchardServices services, IIndexingTaskManager indexingTasks)
        {
            this.contentManager = contentManager;
            this.cultureManager = cultureManager;
            this.emailManager = emailService;
            orchardServices = services;
            _indexingTasks = indexingTasks;

            Logger = NullLogger.Instance;
        }

        // GET: ResourceForm
        [HttpGet]
        public ActionResult Index(int? ResourceID)
        {
            actualLanguage = orchardServices.WorkContext.CurrentCulture;

            var model = new ResourceRequestViewModel
            {
                ResourceToAdd = new ResourceViewModel
                {
                    ResourceNamesList = new List<SelectListItem>(),
                    ResourceTypesList = new List<SelectListItem>()
                },
                actualLanguage = actualLanguage
            };
            model.ResourceToAdd.Count = 1;
            model.ResourceToAdd.ResourceTypesList = GetResourceTypes();
            model.ResourceToAdd.ResourceNamesList = GetResourceNames(int.Parse(model.ResourceToAdd.ResourceTypesList.FirstOrDefault().Value));
            model.AddedResources = new List<ResourceViewModel>();
            if (ResourceID.HasValue)
            {
                model.AddedResources.Add(AddResourceToModel(ResourceID.Value, 1));
            }


            model.AvailableLanguages = cultureManager.ListCultures().Where(x => x != actualLanguage);

            var settings = orchardServices.WorkContext.CurrentSite.As<ReCaptchaSettingsPart>();
            model.PublicKey = settings.PublicKey;
            model.ShowIfLogged = !settings.TrustAuthenticatedUsers;

            return View(model);
        }


        [HttpPost]
        public ActionResult Index(ResourceRequestViewModel model, string AddResource, string Send, string Cancel, string RemoveResource, int? RemoveId)
        {

            bool reset = false;
            var settings = orchardServices.WorkContext.CurrentSite.As<ReCaptchaSettingsPart>();
            actualLanguage = model.actualLanguage;
            model.ResourceToAdd.ResourceTypesList = GetResourceTypes();
            model.ResourceToAdd.ResourceNamesList = GetResourceNames(model.ResourceToAdd.ResourceType);
            model.AvailableLanguages = cultureManager.ListCultures().Where(x => x != actualLanguage);

            if (AddResource != null)
            {
                RemoveErrors();


                model.ResourceToAdd.ResourceType = int.Parse(model.ResourceToAdd.ResourceTypesList.FirstOrDefault().Value);
                model.ResourceToAdd.ResourceNamesList = GetResourceNames(int.Parse(model.ResourceToAdd.ResourceTypesList.FirstOrDefault().Value));
                ModelState.Remove("ResourceToAdd.ResourceType");
                ModelState.Remove("ResourceToAdd.Count");
                if (model.AddedResources == null)
                    model.AddedResources = new List<ResourceViewModel>();
                model.AddedResources.Add(AddResourceToModel(model.ResourceToAdd.ResourceName, model.ResourceToAdd.Count));
            }

            if (Send != null && ModelState.IsValid)
            {
                var valid = true;
                if (!User.Identity.IsAuthenticated || !settings.TrustAuthenticatedUsers)
                {
                    var result = ExecuteValidateRequest(
                        settings.PrivateKey,
                        orchardServices.WorkContext.HttpContext.Request.ServerVariables["REMOTE_ADDR"],
                        model.recaptcha_challenge_field,
                        model.recaptcha_response_field
                        );
                    valid = HandleValidateResponse(null, result);
                }

                if (!valid)
                {
                    ModelState.AddModelError("Captcha", ("You did not type the verification word correctly. Please try again."));
                }
                else
                {
                    ContentItem request;

                    request = contentManager.New("ResourceRequest");


                    request.As<TitlePart>().Title = model.Name;

                    contentManager.Create(request);

                    FillRequest(request, model);

                    contentManager.Publish(request);
                    _indexingTasks.CreateUpdateIndexTask(request);

                    var metadata = contentManager.GetItemMetadata(request);
                    var index = Request.Url.AbsoluteUri.IndexOf(Request.Url.AbsolutePath, StringComparison.Ordinal);
                    var basePath = Request.Url.AbsoluteUri.Substring(0, index);
                    if (basePath.EndsWith("/"))
                        basePath = basePath.Substring(0, basePath.Length - 1);
                    basePath += Request.ApplicationPath;
                    var path = (String.Format("{0}/{1}/{2}/{3}/{4}", basePath, metadata.DisplayRouteValues["area"], metadata.DisplayRouteValues["controller"], metadata.DisplayRouteValues["action"], metadata.DisplayRouteValues["Id"]));
                    try
                    {
                        var body = String.Format("Podrobnosti o požiadavke na rezerváciu kapacity nájdete na: {0}", path);

                        const string subject = "AgroBioTech portál: Bola vytvorená nová požiadavka na rezerváciu kapacity";
                        var recipients = GetRecipients(model);
                        emailManager.Send(body, subject, recipients);
                    }
                    catch (NullReferenceException)
                    {
                        //cele toto zmazat po fixnuti
                    }
                    model.Result = 1;
                }
            }
            if (RemoveResource != null)
            {
                if (RemoveId.HasValue)
                {
                    model.AddedResources.RemoveAt(RemoveId.Value);
                }
            }

            if (Cancel != null)
            {

            }

            if (model.AddedResources == null)
                model.AddedResources = new List<ResourceViewModel>();

            model.PublicKey = settings.PublicKey;
            model.ShowIfLogged = !settings.TrustAuthenticatedUsers;
            return View(model);
        }

        [ValidateAntiForgeryToken]
        public ActionResult ResourceTypeChanged(string selection)
        {
            var typeId = int.Parse(selection);
            var data = GetResourceNames(typeId);
            return Json(data);
        }

        /// <summary>
        /// Adds new resource to the form.
        /// </summary>
        /// <param name="model">The model.</param>
        /// <returns></returns>
        [ValidateAntiForgeryToken]
        public ActionResult AddResource(ResourceRequestViewModel model)
        {
            return Json("");
        }

        /// <summary>
        /// Gets the recipients.
        /// </summary>
        /// <param name="model">The model.</param>
        /// <returns></returns>
        private string GetRecipients(ResourceRequestViewModel model)
        {
            string recipients = "";
            var employees = contentManager.Query().ForType("Employee").List();
            if (model.AddedResources != null)
            {
                foreach (var resourceVievModel in model.AddedResources)
                {
                    if (resourceVievModel.emailList != null)
                    {
                        var ids = resourceVievModel.emailList;

                        if (ids != null)
                        {
                            foreach (var id in ids)
                            {
                                try
                                {
                                    int id1 = id;
                                    var employee = employees.FirstOrDefault(x => x.Id == id1);
                                    var employeeItem = (dynamic)employee;
                                    string email = employeeItem.Employee.Primaryemail.Value;
                                    if (email != null)
                                    {
                                        if (!recipients.Contains(email))
                                        {
                                            if (recipients != "")
                                                recipients += ", ";
                                            recipients += email;
                                        }
                                    }
                                }

Softea.ResourceForm/Views/ResourceForm/Index.cshtml
@using Softea.ResourceForm.ViewModels
@model ResourceRequestViewModel

@{
    Style.Include("ResourceForm.min.css");
    Script.Require("jQuery");
    Script.Require("jQueryUI_Core");
    using (Script.Foot())
    {
        <script type="text/javascript">
    $('#ResourceToAdd_ResourceType').change(function () {
        var selectedValue = $('#ResourceToAdd_ResourceType').val();
        var form = $('#__ResourceRequestForm');
        var token = $('input[name="__RequestVerificationToken"]', form).val();

        $('#dropDownLoader').html("<img src='" + '@Url.Content("~/Modules/Softea.ResourceForm/Styles/images/loader.gif")' + "' />");
        $('#ResourceToAdd_ResourceName').prop("disabled", true);
        $.ajax({
            type: "POST",
            url: '@Url.Action("ResourceTypeChanged", "ResourceForm")',
                    data: {
                        __RequestVerificationToken: token,
                        selection: selectedValue
                    },
                    success: function (data, status) {
                        var select = $('#ResourceToAdd_ResourceName');
                        select.html("");
                        $.each(data, function (val, text) {
                            select.append(
                                $('<option></option>').val(text.Value).html(text.Text)
                            );
                        });
                        if (data.length == 0) {
                            $('#AddResource').prop("disabled", true);
                        } else {
                            $('#AddResource').prop("disabled", false);
                        }
                        $('#ResourceToAdd_ResourceName').prop("disabled", false);
                        $('#dropDownLoader').html("");
                    },
                    error: function (data) {

                        //todo: informovat o zlyhani
                        console.log(data);
                        $('#ResourceToAdd_ResourceName').prop("disabled", false);
                        $('#dropDownLoader').html("");
                    }
                });
            });
            $('#__ResourceRequestForm').on("click", '#RemoveResource', function () {
                $(this).append('<input type="hidden" name="RemoveId" value="' + this.className + '" >');
            });

        </script>
    }
}

<div class="content-localization">
    <div class="content-localizations">
        <h4>@T("Translations:")</h4>
        <ul class="localizations">
            @foreach (var _ in Model.AvailableLanguages.Select((culture, index) => new { culture, index }))
            {
                <li>
                    @switch (_.culture)
                    {
                        case "sk-SK":
                            @Html.ActionLink("Slovenčina", "Index", "ResourceForm", new { culture = _.culture }, null)
                            break;
                        case "en-US":
                        @Html.ActionLink("English", "Index", "ResourceForm", new { culture = _.culture }, null)
                            break;
                        default:
                        @Html.ActionLink(_.culture, "Index", "ResourceForm", new { culture = _.culture }, null)
                            break;
                    }
                </li>
            }
        </ul>
    </div>
</div>

@if (Model.Result == 1)
{
    <div class="success">@T("You have created resource request")</div>
}
@using (Html.BeginFormAntiForgeryPost(null, FormMethod.Post, new { id = "__ResourceRequestForm" }))
{
    @Html.HiddenFor(m => m.actualLanguage)
    <h1>@T("Resource Reservation Request")</h1><br />
    <h3>@T("Applicant")</h3>
    <table class="summary">
        <tr>
            <td>@T("Name and surname / business name")</td>
            <td>@Html.EditorFor(m => m.Name)</td>
            <td>
                @if (ViewContext.ViewData.ModelState.ContainsKey("Name") && ViewContext.ViewData.ModelState["Name"].Errors.Count > 0)
            {
                <span class="error">@T("Please fill out this required field")</span>
            }
        </td>
    </tr>
    <tr>
        <td>@T("Web Page URL")</td>
        <td>@Html.EditorFor(m => m.URL)</td>
        <td>
            @if (ViewContext.ViewData.ModelState.ContainsKey("URL") && ViewContext.ViewData.ModelState["URL"].Errors.Count > 0)
                {
                <span class="error">@T("Please fill out this required field")</span>
            }
        </td>
    </tr>
    <tr>
        <td>@T("E-mail")</td>
        <td>@Html.EditorFor(m => m.Email)</td>
        <td>
            @if (ViewContext.ViewData.ModelState.ContainsKey("Email") && ViewContext.ViewData.ModelState["Email"].Errors.Count > 0)
                {
                <span class="error">@T("Invalid email address")</span>
            }
        </td>
    </tr>
    <tr>
        <td>@T("Phone")</td>
        <td>@Html.EditorFor(m => m.Phone)</td>
        <td>
            @if (ViewContext.ViewData.ModelState.ContainsKey("Phone") && ViewContext.ViewData.ModelState["Phone"].Errors.Count > 0)
                {
                <span class="error"> @T("Please fill out this required field")</span>
            }
        </td>
    </tr>
    <tr>
        <td>@T("Business Area")</td>
        <td>@Html.TextAreaFor(m => m.BusinessSubject, new { cols = "35", rows = "3" })</td>
        <td>
            @if (ViewContext.ViewData.ModelState.ContainsKey("BusinessSubject") && ViewContext.ViewData.ModelState["BusinessSubject"].Errors.Count > 0)
                {
                <span class="error">@T("Please fill out this required field")</span>
            }
        </td>
    </tr>
    <tr>
        <td>@T("Period Required")</td>
        <td>@Html.TextAreaFor(m => m.Period, new { cols = "35", rows = "3" })</td>
    </tr>
    <tr>
        <td>@T("Request Description")</td>
        <td>@Html.TextAreaFor(m => m.Description, new { cols = "35", rows = "3" })</td>
    </tr>
</table>

    <br />
    <h3>@T("List Of Requested Resources")</h3>
    if (Model.AddedResources.Count > 0)
    {
        <table id="resources" class="resources">
            <tr>
                <th>@T("Resource")</th>
                <th>@T("Requested Count")</th>
                <th>@T("Available Capacity")</th>
                <th>@T("Available Externally")</th>
                <th></th>
            </tr>
            @for (int i = 0; i < Model.AddedResources.Count; i++)
            {
                <tr>
                    <td>
                        @Html.HiddenFor(m => m.AddedResources[i].Id) @Html.HiddenFor(m => m.AddedResources[i].Name)
                        <strong>@Html.DisplayFor(m => m.AddedResources[i].Name)</strong>
                    </td>
                    <td>
                        <span class="count">@Html.TextBoxFor(m => m.AddedResources[i].Count, new { @class = "count" })</span>
                        @if (Model.AddedResources[i].emailList != null)
                        {
                            for (int k = 0; k < Model.AddedResources[i].emailList.Count; k++)
                            {
                                @Html.HiddenFor(m => m.AddedResources[i].emailList[k])
                            }
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(m => m.AddedResources[i].AvailableCapacity)
                        @Html.HiddenFor(m => m.AddedResources[i].AvailableCapacity)
                    </td>
                    <td>
                        @(Model.AddedResources[i].IsAvailableExternally ? @T("Yes") : @T("No"))
                        @Html.HiddenFor(m => m.AddedResources[i].IsAvailableExternally)
                    </td>
                    <td><input type="submit" name="RemoveResource" id="RemoveResource" class="@i" value="@T("Remove")" /></td>
                </tr>
            }
        </table>
    }
    else
    {
        <p>@T("No resources included.")</p>
    }

    <br /><br />
    <h3>@T("Add Resource To List")</h3>
    <table>
        <tr>
            <td>@Html.DropDownListFor(m => m.ResourceToAdd.ResourceType, Model.ResourceToAdd.ResourceTypesList)</td>
            <td>@Html.DropDownListFor(m => m.ResourceToAdd.ResourceName, Model.ResourceToAdd.ResourceNamesList)<span id="dropDownLoader"></span></td>
            <td>
                @T("Requested Count")
                <span class="count">@Html.EditorFor(m => m.ResourceToAdd.Count, new { @class = "count" })</span>
            </td>
            <td>
                @if (Model.ResourceToAdd.ResourceNamesList.Count > 0)
                {
                    <input type="submit" name="AddResource" id="AddResource" value="@T("Add")" width="30px" />
                }
                else
                {
                    <input type="submit" name="AddResource" disabled="disabled" id="AddResource" value="@T("Add")" />
                }
            </td>
        </tr>
    </table>
    <br />
    <br />
    if (!User.Identity.IsAuthenticated || Model.ShowIfLogged)
    {
        <div>
        @{
            using (Script.Head())
            {
                <script type="text/javascript">
                    var RecaptchaOptions = { theme: 'clean' };
                </script>
            }
        }
                <script type="text/javascript" src="//www.google.com/recaptcha/api/challenge?k=@Model.PublicKey"></script>
                

            <noscript>
                <iframe src="//www.google.com/recaptcha/api/noscript?k=@Model.PublicKey" height="300" width="500" frameborder="0"></iframe><br>
                <textarea name="recaptcha_challenge_field" rows="3" cols="40"></textarea>
                <input type="hidden" name="recaptcha_response_field" value="manual_challenge">
            </noscript>
            @if (ViewContext.ViewData.ModelState.ContainsKey("Captcha") && ViewContext.ViewData.ModelState["Captcha"].Errors.Count > 0) {
                 <span class="error">@T("You did not type the verification word correctly. Please try again.")</span>
             }
            </div>
    }
    
    <input type="Submit" value="@T("Submit Resource Reservation Request")" name="Send">
}